# Generated by Django 5.2.1 on 2025-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='store/static/categories/default.png', upload_to='store/static/categories'),
        ),
    ]
